server {
    listen 80;
    server_name nemiahub.eu;

    # Redirige tout le HTTP vers HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nemiahub.eu;

    ssl_certificate /etc/letsencrypt/live/nemiahub.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nemiahub.eu/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    # Gestion des routes Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le Backend
    location /api {
        proxy_pass http://backend:8080/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
