services:

  db:
    image: postgres:16-alpine
    container_name: nemia-db
    environment:
      POSTGRES_DB: nemia_hub
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nemia-network

  backend:
    build: ./Nemia-Core
    container_name: nemia-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nemia_hub
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NEMIA_ADMIN_PASSWORD: ${NEMIA_ADMIN_PASSWORD}
      NEMIA_EMILIE_PASSWORD: ${NEMIA_EMILIE_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - nemia-network

  frontend:
    build: ./Nemia-View
    container_name: nemia-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - nemia-network

networks:
  nemia-network:
    driver: bridge

volumes:
  postgres_data: