export enum FluxCategory {
  // Recettes
  LOYER = 'LOYER',
  CHARGES_REFACTUREES = 'CHARGES_REFACTUREES',
  INDEMNITE_RECUE = 'INDEMNITE_RECUE',
  AUTRE_RECETTE_EXPLOITATION = 'AUTRE_RECETTE_EXPLOITATION',

  // Charges courantes
  ELECTRICITE = 'ELECTRICITE',
  EAU = 'EAU',
  INTERNET = 'INTERNET',
  ASSURANCE = 'ASSURANCE',
  TAXE = 'TAXE',
  COPROPRIETE = 'COPROPRIETE',
  FRAIS_BANCAIRES = 'FRAIS_BANCAIRES',
  HONORAIRES = 'HONORAIRES',
  ENTRETIEN_COURANT = 'ENTRETIEN_COURANT',
  CONSOMMABLES = 'CONSOMMABLES',
  MENAGE = 'MENAGE',
  FOURNITURES = 'FOURNITURES',
  AUTRE_CHARGE_EXPLOITATION = 'AUTRE_CHARGE_EXPLOITATION',

  // Travaux / immobilisations
  TRAVAUX = 'TRAVAUX',
  REPARATION_IMPORTANTE = 'REPARATION_IMPORTANTE',
  AMELIORATION = 'AMELIORATION',
  MOBILIER = 'MOBILIER',
  ELECTROMENAGER = 'ELECTROMENAGER',
  EQUIPEMENT = 'EQUIPEMENT',
  DECORATION = 'DECORATION',

  // Financement
  FRAIS_FINANCEMENT = 'FRAIS_FINANCEMENT',
  EMPRUNT_INTERETS = 'EMPRUNT_INTERETS',
  EMPRUNT_ASSURANCE = 'EMPRUNT_ASSURANCE',
  EMPRUNT_CAPITAL = 'EMPRUNT_CAPITAL',

  // Mouvements financiers
  APPORT = 'APPORT',
  RETRAIT = 'RETRAIT',
  VIREMENT_INTERNE = 'VIREMENT_INTERNE',

  // Divers
  REGULARISATION = 'REGULARISATION',
  AUTRE = 'AUTRE',
}
